### ISSUE TITLE
Full game locked on Demo mode

### ISSUE THREAD

**Issue by Zangetsu38** [Vita3K/Vita3K#1233]
i have see one things strange, some game is locked on demo mode, 
i update it after i found any new, other user can also add other game

Is if any game ask for buy full game/unlock full game
- No idea if relate function missing or any other things

#  Game list:
- Rayman Origin
- Jet Set radio
- Pinball arcade

**Comment by hobyst** [comment]
Those three games use Sony's integrated demo+full game system on the PlayStation Store instead of the split demo//full game system like other games such as Gravity Rush use (with individual TITLE_IDs for each one), which makes me think that in this kind of games the base game activation only enables the demo of the game and you need an `addcont` item to actually unlock the full game. We would also need Vita3K to load `addcont` items to test it anyway.

How Rayman origins shows up on the store (integrated demo and full game system):
![](https://user-images.githubusercontent.com/48522412/114833689-24bc2300-9dd0-11eb-8a42-6bafb2db3b3a.png)

How the demo of Gravity Rush looks on the store:
![](https://user-images.githubusercontent.com/48522412/114833815-43bab500-9dd0-11eb-9df5-eefcbaeb4b71.png)

How Gravity Rush looks on the store:
![](https://user-images.githubusercontent.com/48522412/114834009-719ff980-9dd0-11eb-97aa-d4e0b745c856.png)

**Comment by Zangetsu38** [comment]
Oh thx i have forget check this, but problème il have no see any addcont file try open etc

**Comment by Zangetsu38** [comment]
With other dev i have founded solution and know i thinks for how can set this and so now i can unlock full game mode
![image](https://cdn.discordapp.com/attachments/832665175218978877/832705748400078918/unknown.png)

**Comment by Zangetsu38** [comment]
Implemented by pr #1236, close issue
