### ISSUE TITLE
Playback rate unimplemented and crackling audio

### ISSUE THREAD

**Issue by pent0** [Vita3K/Vita3K#1411]
- Audio playback rate in two decoding modules (PCM and AT9) is ignored, results in some games having the Alvin Simon Theodore symptoms (chipmunking).
- Audio that is decoded with AT9 somehow has weird cracklings decoded from FFMPEG. This is unsure if a backend issue or emulator issue.

**Comment by hobyst** [comment]
Testing FFmpeg `.at9` decoding side by side with [VGAudio](https://github.com/Thealexbarney/VGAudio) decoder implementation which is based on [`libatrac9`](https://github.com/Thealexbarney/LibAtrac9) evidences that FFmpeg has timing issues decoding Atrac9 files as it adds silence both at the beginning and the end of decoded files.
![imagen](https://user-images.githubusercontent.com/48522412/123000071-5abceb00-d3af-11eb-88db-a97ac3a0e64a.png)
And not only that, but seems that invalid data is quite common in Atrac9 audio files, as pointed on a [release note from VGAudio](https://github.com/Thealexbarney/VGAudio/releases/tag/v2.2.1) and FFmpeg seems to struggle a lot with this.

Leaving that aside, I think the crackling on audio has more to do with an issue with the audio stream (ex. audio latency due to SDL) and NGS rather than with audio decoding. The HLE audio out module as of today has functions such as [`sceAudioOutSetConfig`](https://docs.vitasdk.org/group__SceAudioUser.html#ga11a4df4d66bfaaf4a50f15d1d4d74a2a) and [`sceAudioOutGetConfig`](https://docs.vitasdk.org/group__SceAudioUser.html#gadfae507c89fda662493734dcb8b51bbd) which allow to check and change audio out port configuration while the port is still open unimplemented.

With all of this I would say that:
- SDL audio has been known for a while to cause several audio latency issues that might eclipse other audio issues and getting rid of it should help to test and refine things on the audio backend. Libraries like [PortAudio](https://github.com/PortAudio/portaudio) should do the job for desktop target platforms while for mobile native audio extensions could be used via C++ (Android NDK) and Swift's interop with C++ (for iOS). This should be fixed the first, as the crackling issues might be at fault of latency on the audio output rather than from Atrac9 decoding.
- FFmpeg Atrac9 decoder has issues and using `libatrac9` might make an improvement.
- Fully implementing the Atrac9 and PCM decoders (after the implementation of `libatrac9` has been done???) should improve latency issues as well, specially with the playback rate being ignored which is necessary to sync the output port frequency to the frequency the game is streaming audio at.
- Fully implement `sceAudio` (audio output port module) in order to allow the audio output port created in the host environment to keep up to with the changes requested by the game in order to improve audio playback.

Due to most of this changes requiring modifications on the audio backend I would suggest to first go with the SDL to PortAudio transition because working on `sceAudio` before the transition would later require a full re-write of the module implementation which if done after it would only require to re-write the already implemented functions and anything new would already use PortAudio. After that, the encoding issues and the playback rate sync could be worked on without having to worry about the hypothetical latency caused by SDL.

As a side note, inspecting the metadata of several `.at9` using MediaInfo gave me the conclusion that a lot of the files aren't mono but joint stereo files. I don't know how and if the emulator or FFmpeg handle this, but it's a major thing to keep in mind for the decoder.

**Comment by Zangetsu38** [comment]
second point is fixed now :D, keep need fix playback speed voice inside player

**Comment by hobyst** [comment]
With #1577 now merged, playback rate scaling is fixed but audio crackling still persists. Example: https://github.com/Vita3K/compatibility/issues/222#issuecomment-1036507684

**Comment by Zangetsu38** [comment]
Thus crackely depending game, senran kagura is good

**Comment by PepperWithMint** [comment]
Hi, is this audio bug issue still unsolved?

**Comment by Zangetsu38** [comment]
is half implemented for some game using playaback rate value in player, missing at9 for now

**Comment by IrisHeartCPU** [comment]
Hi,, i've been playing Muramasa Rebirth and happens too on it, also the log says it has at9
<img width="666" alt="Captura" src="https://user-images.githubusercontent.com/61751545/182889622-b488d96c-62df-4b94-9b46-afb3bf79b19c.PNG">
<img width="960" alt="Captura de pantalla 2022-08-04 174035" src="https://user-images.githubusercontent.com/61751545/182889635-91e76d96-8cec-47e8-8202-5012fd736fa5.png">

**Comment by Zangetsu38** [comment]
is old log, no have any crackly now normally

**Comment by IrisHeartCPU** [comment]
> is old log, no have any crackly now normally

what log? my log is from now

**Comment by Emalcat** [comment]
![Cattura](https://user-images.githubusercontent.com/88663610/223756169-697d0294-090c-4ecd-95ca-a917c41ddcd9.PNG)
Happnens to me too, Right now Persona 4 Golden and Muramasa Rebirth's sound is really crackle-ey
Gravity Rush instead sounds normal

**Comment by ajchimaera** [comment]
Been playing Persona 4 Dancing All Night and the audio crackle is persistent. Can mitigate in gameplay by disabling extra sounds like voices and notes, but that reduces some of the fun of playing the game.

**Comment by mdsmendes94** [comment]
Audio still crackling on the latest release, tested with both cubeb and sdl

[vita3k.log](https://github.com/Vita3K/Vita3K/files/11472098/vita3k.log)

**Comment by pent0** [comment]
😀😀😀

**Comment by ISuckGood** [comment]
I have this issue in ar no surge latest version .

The currently running game requests playback rate scaling when decoding audio. Audio might crackle

Sound crackle

**Comment by piau9000** [comment]
This should be reopened, as some games are still bugged. One of them is Dynasty Warriors Next. It shows the same error about "request playback rate scaling".

**Comment by raeldor** [comment]
I am noticing pretty significant crackling in Sora no Kiseki FC Evolution on Android.
