### ISSUE TITLE
Locale Issue and workaround

### ISSUE THREAD

**Issue by Godsbane** [Vita3K/Vita3K#2092]
Hiya,

Was testing the builds on steamOS, and found that if a user has set their locale to anything but en_US, Vita3K will throw an error.

I validated by changing my locale, and then trying to run it as well.
![image](https://user-images.githubusercontent.com/1683513/192375573-a4f98b8f-36ec-49fc-99a8-57dbacfe4ab4.png)

Also replicated this way:
`LANG=fr_FR.UTF-8 ./Vita3K `
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)
```

When running under en_US, everything is fine. I just wanted to bring it to your attention.

**Comment by Zangetsu38** [comment]
No can help here,  is linux probleme, no idea, maybe other dev can look

**Comment by EXtremeExploit** [comment]
this is known, this is because SteamOS only generates the locales for `en_US.UTF-8`, there is nothing we can do afaik.
stacktrace in case you are interested. running with ungenerated `es_ES.UTF-8`
![image](https://user-images.githubusercontent.com/30161277/192384266-289a35e0-0ebf-464c-a8bf-0d5cf5999f96.png)
closing as there is nothing we can do, its very specific and running programs with non-generated locale is undefined behaviour

**Comment by Godsbane** [comment]
Thank you for looking at it. I will script it to use en_US via env variables :)

**Comment by cmalvi** [comment]
If you run Vita3k from Steam, no error about locale (so no problem to run it from game mode)

**Comment by Godsbane** [comment]
This is ok, except for the parts where the person needs to install things with file pickers, and steam doesn't show them in game mode. I'll put it together with locale in the launcher just in case they need it from desktop.

**Comment by cmalvi** [comment]
> This is ok, except for the parts where the person needs to install things with file pickers, and steam doesn't show them in game mode. I'll put it together with locale in the launcher just in case they need it from desktop.

It also works from desktop, just launch it using steam
