### ISSUE TITLE
[Feature Request] Option to turn off "Compiling Shaders" notification in the screen

### ISSUE THREAD

**Issue by rrrcabral** [Vita3K/Vita3K#2472]
i think it is very distracting.

**Comment by Zangetsu38** [comment]
I have code it for good reason so no

**Comment by rrrcabral** [comment]
> I have code it for good reason so no

RPCS3 has coded this too, and gives you the option to turn it off,
and continues to be recognized as a great emulator.
the original hardware doesn't have shader notifications on the screen, and the goal of an emulator wasn't to get as close to the original hardware as possible, was it?
that's what makes a great emulator.

**Comment by CoffeeBrewer64** [comment]
rpcs3 isn't a good emulator/debugger because of a single "compiling shaders..." message being able to be hidden. and of course the consoles don't have a "compiling shaders..." message.

vita3k isn't 100% accurate to the vita.
RPCS3 isn't 100% accurate to the ps3.

a single message won't change the way the emu works, this is seriously trivial.

**Comment by Croden1999** [comment]
> > i think it is very distracting.
> 
> i fork the respo, then delete the "compiling shader" , github actions auto-generated the exe program, u can have a try. https://github.com/cxhttt233/Vita3K/actions/runs/4964439693

does not make sense

**Comment by Zangetsu38** [comment]
lol what is this
