### ISSUE TITLE
DualSense Edge not recognized

### ISSUE THREAD

**Issue by kin-patsu** [Vita3K/Vita3K#2488]
As by title, the emulator doesn't recognize the DualSense Edge, returning "No compatible controllers connected. Connect a controller that is compatible with SDL2" when checking under Controls -> Controllers

**Comment by nn9dev** [comment]
This might be because the external SDL hasn't been updated to a more recent SDL. From what I can tell, DualSense Edge support was added in October (https://github.com/libsdl-org/SDL/pull/6444/commits/89b51b668f62167b70f0e9315e33e1b6dbc90b9b), and Vita3K's last SDL update was in August (https://github.com/Vita3K/sdl/commit/7f4fa3f79a003f1e2b14a9a32dab3e86ff97d801).

**Comment by Zangetsu38** [comment]
oh, need sdl update :

**Comment by Zangetsu38** [comment]
@kin-patsu test this pr
https://github.com/Vita3K/Vita3K/pull/2489

**Comment by Zangetsu38** [comment]
Should be fixed in last master
