### ISSUE TITLE
Steam Deck Multi-touch not working 

### ISSUE THREAD

**Issue by Krules02** [Vita3K/Vita3K#2711]
Vita3k should already have multi-touch support according to #407. But on the steam deck (with "native touchscreen support" enabled), I am unable to use the touch screen at all. It seems others have mentioned the same issue with steam deck support in #2653.

**Comment by poudink** [comment]
I don't know about multi-touch support since I don't have any games that use multi-touch, but I can tell you that native touch screen support does work. Vita3k is just really weird about it. For whatever reason, it's toggled off by default. You need to toggle it on using whatever key you have binded to "Toggle Touch", which by default is T.

**Comment by Kurt13Yves** [comment]
I tried to play gravity rush again today and seems like the multi-touch now works on steam deck

**Comment by Krules02** [comment]
Updated vita3k and it works for me now too
