### ISSUE TITLE
Support lower OpenGL versions

### ISSUE THREAD

**Issue by johnny-mac** [Vita3K/Vita3K#279]
Hello again, I just tried compiling & installing vita3k on my laptop running Void MUSL.... It compiled successfully, but gives me an error when trying to launch it - " |E| [init]: Could not create OpenGL context." 

This is using the latest git clone of vita3k, perhaps there's a dependency in the externals folder that needs to be disabled so vita3k can compile against something within the system? IDK.

One of you mentioned Discord/IRC/etc for "support", I would love to know where I can find that support channel. thank you.

**Comment by johnny-mac** [comment]
You say at the moment... Will you be supporting previous versions of vita3k in the future? 
I think my laptop unfortunately doesn't support OpenGL 4.1, its an intel i5 ironlake M 520 using the i915 driver. And thank you for the link, I'm gonna have to try getting my headset working unless you guys don't mind reading, idk how that works in discord.

**Comment by bentokun** [comment]
Maybe previous version will be supported. I can't promise it :(

**Comment by mrcmunir** [comment]
Intel ironlake gpu is very old gpu from 2010 is only support Opengl 2.1 (Windows//Opengl es 2.0 (Under Linux with recents drivers) .
So this gpu is limited 120 GLSL only .

**Comment by Degerz** [comment]
I think we should just close this issue and use Vulkan instead which will eventually come with OpenGL style fragment shader interlocks. The feature will enable the devs behind this emulator to be able to emulate **ANY** framebuffer formats inside a pixel shader much like how the original Vita hardware was [capable](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_shader_framebuffer_fetch.txt) of arbitrarily reading the framebuffer data from the shader ... 

Some of the infrastructure is already in place such as using a Spir-V intermediate representation to translate gxm shaders into GLSL shaders. We can cover macOS by using moltenVK which will grant the team more useful features for emulation like getting access to Metal's raster order groups [functionality](https://developer.apple.com/documentation/metal/mtldevice/ios_and_tvos_devices/about_gpu_family_4/about_raster_order_groups) so that some macOS systems will be able to also emulate the Vita's blending capabilities. There's really not much reason to target Apple's deprecated OpenGL implementation when it arguably makes more sense from a features/maintainability perspective to target a translation layer instead IMO ...

**Comment by Zangetsu38** [comment]
Use vulkan good idea, but hmm maybe to early for that ^^

**Comment by Degerz** [comment]
@Zangetsu38 It's probably not too early IMO ... 

It's a very high possibility that Apple's OpenGL implementation could very well become a big blocker in the not too distant feature when they will probably need programmable blending. D3D12 ROVs/GL or VK fragment shader interlocks/MTL raster order groups are **NOT** available on Apple's OpenGL implementation ... 

It's absolutely paramount that the devs behind this emulator have access to a similar feature ...

**Comment by pent0** [comment]
There are devs that are still using their Mac as their main development environment. Of course that we can working on Vulkan along with OpenGL, but no one have touch Vulkan and be experienced enough with it here.

Maybe in the future, but what is Vulkan and apple stuff doing here? We are not mentioning it anywhere in this thread.

**Comment by 1whatleytay** [comment]
So are you suggesting to drop Mac support entirely? Apple doesn't support Vulkan at all, unless you count MoltenVK which isn't perfect by any means. I think it would be best to focus on getting OpenGL working entirely before using other APIs.

**Comment by Degerz** [comment]
The reason why I mention Apple is because their implementation obviously only supports OpenGL 4.1 and the reason why I mention Vulkan is because targeting OpenGL and especially it's older versions is a bad ideal ... 

Not saying you guys should drop Mac support entirely but it's preferable to find another way to do it such as using MoltenVK. MoltenVK might end up being better for your use case if you guys do end up needing fragment shader interlock or a similar functionality ...

**Comment by pent0** [comment]
Or you could just tell that to close this issue and use higher OpenGL version...
I still appreciate the idea, but we can't do it right now, none of us are good with Vulkan. Sorry.

**Comment by Degerz** [comment]
It's fine if you guys aren't good with Vulkan right now but I'm a little bit iffy on the idea of using an API implementation that might not give all the features you want for your use case ...

**Comment by pent0** [comment]
The time will come if it's needed. No need to worry.

**Comment by VelocityRa** [comment]
@Degerz This is not a discussion for this place. Please join [our Discord](https://discord.gg/MaWhJVH) and let's continue there.

**Comment by VelocityRa** [comment]
I'm not sure why would we need fragment shader interlocks?
And what does Vulkan have to do with any of this? It's all possible with OpenGL as you said.
I don't see Vulkan happening for years, if not ever. It's extremely more work than OpenGL for little benefit.
Anyway, please ping me (`@velocity`) on Discord to discuss further.

**Comment by pent0** [comment]
We can't lower it down more, more features and exclusive texture formats are discovered. The bar might even be raised up, but not now. Not sure why don't close this
