### ISSUE TITLE
IOS Support

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [Vita3K/Vita3K#2994]
It'd be great to have an ios port for this emulator, to add to my collection for ps1 retroarch, ps2 play, and psp ppsspp I think my 14 pro max will run 2d and even 3d games. It'll be great to play undertale, puyo puyo tetris, psasbr, and more on the go.

**Comment by EXtremeExploit** [comment]
itd also be great if apple even supported side loading and didnt require a mac to develop for it, but it is what it is, gonna close as theres really nothing we can do, may reopen once they support sideloading and someone has the insane balls of porting it to iOS that owns a mac. otherwise not happening anytime soon nor in anyones plans

**Comment by nn9dev** [comment]
As the only one who owns an iOS device out of all 36,000 people in the Vita3K server, I can echo the sentiments of Extreme from a development standpoint. Porting this to iOS would require a Mac and none of the lead developers on this project own one, nor do I believe they want to spend the money to purchase one. Apple also IS stingy with sideloading, not to mention that it would require JIT and thus a JIT solution like AltJIT to make it run at any _good_ framerate (which is... annoying... to say the least...)

I believe one person took a crack at it at some point, but we never heard from them after initial efforts. Maybe it'll happen one day, but probably not soon.

**Comment by Iamthebestintheworld222** [comment]
I'm running iOS 16.7 which has jit support from AltStore. iOS 17 doesn't.
