### ISSUE TITLE
[BUG]: Linux build is forced to take precompiled ffmpeg binaries

### ISSUE THREAD

**Issue by v-fox** [Vita3K/Vita3K#3257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

20240319T211715.cb15157c

### Description of Issue

After recent update, likely https://github.com/Vita3K/Vita3K/pull/3249, Vita3K started to demand downloading archive with precompiled binaries which is one of the biggest No-No'es of open-source which should never-ever be done.
It was bad enough that system ffmpeg could not be linked but not properly building the whole binary is simply terrible which makes it practically unpackageable in distros.

### Expected Behavior

At least present the sources of the fork, if not linking to system library.

### Reproduction Steps

Try to compile.

### Log File

Downloading files during builds is also violation of [Open Build Service](https://en.wikipedia.org/wiki/Open_Build_Service)'s workflow rules. Which is what failed the build initially.
I've put the archive manually as work around but using binaries is still a quality violation.

### System Configuration

CPU: virtual machine used to build a package
GPU/Driver: virtual machine used to build a package
RAM: virtual machine used to build a package
OS: GNU/Linux

**Comment by Macdu** [comment]
Prebuilt ffmpeg binaries were being used ever since Vita3K was release. It's just that previously the prebuilt were directly in the github repository (which was pretty bad) while now only the appropriate prebuilt is being downloaded when cmake is first run.

Also it's not like you have no idea how the prebuilts were generated, all of them are automatically generated on each new update by a CI and the code run on the CI to generate the libraries is available on the github repository.

**Comment by v-fox** [comment]
> Also it's not like you have no idea how the prebuilts were generated, all of them are automatically generated on each new update by a CI and the code run on the CI to generate the libraries is available on the github repository.

Open-source is not ran on faith, it's ran on open source and there is no source. This downgrades whole project in effectively "proprietary freeware". Also, GPL requires you to publish all source used.

>  and the code run on the CI to generate the libraries is available on the github repository.

1) I don't know where it supposed to be, but it doesn't seem to be in `external/ffmpeg` or `Vita3K/ffmpeg-core/tree/master`.
2) Even if it was tucked somewhere and formal GPL requirement met, it's still horrible maintenance and disrespect to intent of GPL.

**Comment by KhoraLee** [comment]
> I don't know where it supposed to be, but it doesn't seem to be in external/ffmpeg or Vita3K/ffmpeg-core/tree/master.

1. VCPKG downloads ffmpeg code from ffmpeg's github mirror and apply patches. You can see how it is built at Github action's log.
Patches: https://github.com/microsoft/vcpkg/tree/f6a5d4e8eb7476b8d7fc12a56dff300c1c986131/ports/ffmpeg
Build log: https://github.com/Vita3K/ffmpeg-core/actions/runs/8255509666/job/22582128158

2. ffmpeg is LGPL v2.1 not GPL since we do not pass `--enable-gpl` build option.

3. Other OSS project uses such prebuilt library download process. For example IINA uses MPV(contains dynamic ffmpeg libraries) and download prebuilts from their private server (https://github.com/iina/iina?tab=readme-ov-file#using-the-pre-compiled-libraries). Also I don't get any difference with using package manager to download other libraries like OpenSSL.

**Comment by patlefort** [comment]
Sneaking in pre-built binaries in a build process in supposedly open source project really is a big nono. If other project do the same, they are also wrong. With all due respect, please fix it. Is it a nightmare for package maintainers on linux.
