### ISSUE TITLE
Flickering black texels on Persona 4 Golden on GeForce RTX GPU

### ISSUE THREAD

**Issue by pent0** [Vita3K/Vita3K#569]
Using fragment shader interlocks, when running P4G on a RTX GPU, we can experience flickering black texels running around. This does not happen on Intel GPU and on GTX GPU drvers afaik.

A video of this happen

https://www.youtube.com/watch?v=Peu_ULHmyTU

Opening it for tracking the progress of fixing

**Comment by pent0** [comment]
https://devtalk.nvidia.com/default/topic/1060807/opengl/-windows-possible-driver-bug-fragment-shader-interlock-has-almost-no-effect-on-rtx-gpu-driver/

Opening one here, I dont think this is our fault, I make a small reproduce with what I believe to be correct, but same things happen on the newest RTX driver.

**Comment by Degerz** [comment]
It looks like you're encountering a race condition on Turing GPUs. I can't tell if this problem is isolated to your case but it would be nice to see if you tested out driver 419.35 as well and see what happens.

**Comment by Degerz** [comment]
Has this issue been resolved yet ? I think we might have to drop the OpenGL backend in favour of the Vulkan backend if this issue isn't fixed by the beginning of next year because it's really important for your team that you have this feature working on vendors who offer it and at least have it functional on all of their GPU families or even potentially functional on future GPU families. 

One caveat to the assumption is that moving to Vulkan might not fix the issue at all on Nvidia since their Vulkan driver shares code with their OpenGL driver.

**Comment by 1whatleytay** [comment]
iirc this has been solved since shadows
