### ISSUE TITLE
VFS emulation

### ISSUE THREAD

**Issue by petmac** [Vita3K/Vita3K#82]

**Comment by VelocityRa** [comment]
Is there anything preventing us from upgrading the project to C++17? Because `std::filesystem` would certainly make things cleaner and easier.

**Comment by petmac** [comment]
I didn't try. If it works on Clang, MSVC and GCC I'd be happy to go to C++17.

**Comment by motoharu-gosuto** [comment]
Here is more general discussion about filesystem design.
Overall description of filesystem is given here: https://wiki.henkaku.xyz/vita/File_Management
If we want to implement filesystem properly we need to consider the following modules:
* SceAppUtil - responsible for mount functions.
* SceAppMgr - responsible for lots of mount functions.
* SceIofilemgr - abstract layer that provides i/o operations.
* SceLibFios2 - i/o scheduling, caching layer. It is extensively used by games. Check this log from frangarcj 
https://pastebin.com/Zcpa56ye
* ScePfsMgr - this is kernel only module responsible for pfs decryption and encryption.
* SceSdstor - this is kernel only module responsible for reading physical devices.

**Comment by motoharu-gosuto** [comment]
I continue thinking about filesystem. How it is implemented in vita and what we should implement on our end. I want to talk about mount points. From what I understand 2 main types of mount points exist. I would call them physical and virtual.
Physical mount points correspond to real partitions on the storage. For example ux0: gro0: os0: and so on. You can find list of partitions here: https://wiki.henkaku.xyz/vita/Partitions

These partitions are usually mounted with https://wiki.henkaku.xyz/vita/SceIofilemgr#sceIoMountForDriver And additional info about mount points is here: https://wiki.henkaku.xyz/vita/SceIofilemgr#Mount_Points

Now about virtual mount points.
I am assuming that Iofilemgr function is not supposed to be used by games.
All physical partitions that are required should be mounted prior to running the game.
Game should only use virtual mount points (they are also called `drives`). Mounting of this drives is the responsibility of AppUtil and more widely AppMgr under the hood.
For example such functions exist:
sceAppUtilExtVideoMount - mounts video0: drive
sceAppUtilSaveDataMount - mounts savedata1: drive
sceAppUtilAddcontMount  - mounts addcont1: drive
sceAppUtilPhotoMount  - mounts photo0: drive
sceAppUtilMusicMount - mounts music0: drive
These drives (when mounted) get mapped to physical locations.
For example addcont1: can be mapped on ux0:addcont/<TITLEID>

Also I am assuming that depending on type of data - drive can be mounted normally or pfs mounted.
There is even a special function for that in Iofilemgr:
https://wiki.henkaku.xyz/vita/SceIofilemgr#scePfsMgrVfsMountForDriver(edited)
However I am still not quite clear how pfs stuff integrates in overall structure.

My initial guess that system does not check which of the mounts to do. This is assumed by design.
For example When you call https://wiki.henkaku.xyz/vita/SceAppMgr#sceAppMgrGameDataMountForDriver 
under the hood it calls 
https://wiki.henkaku.xyz/vita/ScePfsMgr#mount 
which calls https://wiki.henkaku.xyz/vita/SceIofilemgr#scePfsMgrVfsMountForDriver

I am assuming that if you call  https://wiki.henkaku.xyz/vita/SceAppMgr#sceAppMgrPhotoMountForDriver
under the hood it will call different mount function (normal one). Not sure though.

There is also additional layer in the middle managed by AppMgr. We might not need it but I still want to mention it. Not quite sure how it works at the moment though.
When virtual drive is mounted - appmgr generates yet another mount point (which is a temporary identifier that can be used instead of TITLEID. I think so but it is not confirmed).
It consists of prefix like "td", "PD", "ms", "lm" followed by randomly generated string of integers.

This behavior is implemented in single function that is responsible for all mounting and is used by all mount and unmount functions in AppMgr. I still think that it is important to understand how it works because it glues virtual mount points (drives) to physical locations. I am reversing this function here:
https://github.com/motoharu-gosuto/psvcmd56/blob/master/src/CMD56Reversed/SceAppMgr.cpp#L912

get_random_path - up above is the one that is part of it - responsible for generating temporary mount points.

**Comment by pent0** [comment]
It's added, PFS is translated to normal filesystem on installation. All operations are non PFS
