### ISSUE TITLE
Texture Cache / Mapping

### ISSUE THREAD

**Issue by frangarcj** [Vita3K/Vita3K#96]
Can use #94 to make a better texture handling

**Comment by petmac** [comment]
I don't actually think we can map texture data, unless we want to implement texture sampling ourselves, because the texture host texture format will be different to the Vita's.

A texture cache was implemented in #258 which I think is as good as we can get without reimplementing texture sampling.

What do you think?

**Comment by pent0** [comment]
Texture cache added, mapping seems not possible on all API sadly :( Performance can be improved without texture mapping.
